; Generated by AutoGUI 2.5.9
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, GroupBox, x18 y0 w263 h146, Основные настройки
Gui Add, Edit, x24 y20 w50 h21, 30
Gui Add, Edit, x24 y50 w50 h21, F7
Gui Add, Edit, x24 y80 w50 h21, 1
Gui Add, Edit, x24 y111 w50 h21, Челик
Gui Add, Text, x82 y20 w176 h23 +0x200, Сколько в секундах бить босса
Gui Add, Text, x80 y50 w194 h23 +0x200, Клавиша сбора лута (Быстрый сбор)
Gui Add, Text, x80 y79 w157 h23 +0x200, Клавиша атакущего макроса
Gui Add, Text, x80 y111 w173 h23 +0x200, Имя бота (Пишет ему в пм "123")
Gui Add, GroupBox, x289 y0 w334 h153, Константные значения, обычно не требуется менять
Gui Add, Button, x19 y159 w80 h23, Запустить
Gui Add, Edit, x308 y20 w50 h21, 4
Gui Add, Edit, x308 y48 w50 h21, 8
Gui Add, Edit, x308 y77 w50 h21, 3
Gui Add, Text, x364 y20 w209 h23 +0x200, Пауза после телепорта (прогрузка) в сек.
Gui Add, Text, x365 y48 w251 h23 +0x200, Пауза после входа (пока появляется КВ) в сек
Gui Add, Text, x364 y75 w163 h25 +0x200, Пауза между заходами в сек

Gui Show, w685 h197, NirvanaRoute
Return

GuiEscape:
GuiClose:
    ExitApp
